"ci":
  - any: [".github/**/*"]

"core: tests":
  - any: ["src/**/*.test.ts", "src/**/*.spec.ts"]

"core: combinators":
  - any: ["src/combinators/**/*"]

"core: parsers":
  - any: ["src/parsers/**/*"]

"core: base":
  - any: ["src/*"]

"documentation":
  - any: ["website/**/*"]
