labels:
  - name: "ci"
    paths:
      - .github/**/*

  - name: "core: tests"
    paths:
      - any: ["src/**/*.test.ts", "src/**/*.spec.ts"]

  - name: "core: combinators"
    paths:
      - src/combinators/**/*

  - name: "core: parsers"
    paths:
      - src/parsers/**/*

  - name: "core: base"
    paths:
      - src/*

  - name: "documentation"
    paths:
      - website/**/*
