export * from "./endOfInput";
export * from "./endOfLine";
export * from "./failure";
export * from "./lazy";
export * from "./number";
export * from "./regex";
export * from "./string";
export * from "./whitespace";
export * from "./word";
